// SPDX-License-Identifier: Apache-2.0
// NginxRenderer.swift — the pure, golden-testable half of the nginx provider (SC6).
//
// service + ready endpoints → an nginx config fragment for that one service: an `upstream`
// block (the backend pool) and a `server` block (the listener, with `proxy_pass` into the pool
// and passive health directives). Pure and deterministic: the same desired state renders to a
// byte-identical string, which is what lets the applier hash-compare and skip needless reloads,
// and what lets a golden test pin the output.
//
// Correctness baked in here:
//   - Deterministic order: backends are sorted (Endpoint.less) before rendering, so endpoint
//     set equality ⇒ config equality regardless of store iteration order.
//   - Empty-pool form: nginx REJECTS an empty `upstream {}`, so zero ready endpoints renders an
//     explicit no-backends server that returns 503 — a valid config, never a broken upstream.
//     (This is what keeps the listener up, returning a clean 503, mid-rollout when the pool
//     momentarily empties — instead of nginx failing to load.)
//   - https threads the TLS-cert ref through as `ssl_certificate*` (cert provisioning is the
//     secrets/SC9 seam); tcp would be an L4 stream block — recorded as a seam, http/https first.
//
// Foundation-free: plain String assembly. Open-source nginx has no active `health_check`
// directive (nginx-plus only), so health is rendered as passive `max_fails`/`fail_timeout` on
// each server line plus `proxy_next_upstream`, with the configured readiness path noted.

enum NginxRenderer {
    /// The upstream block's name for a service: `<service>_pool` with non-identifier bytes
    /// mapped to `_` so a hyphenated service name (e.g. "web-api") is a legal nginx identifier.
    static func upstreamName(_ service: String) -> String {
        var out: [UInt8] = []
        for b in service.utf8 {
            let isAlnum = (b >= 0x30 && b <= 0x39) || (b >= 0x41 && b <= 0x5A) || (b >= 0x61 && b <= 0x7A)
            out.append(isAlnum ? b : 0x5F)   // '_'
        }
        return String(decoding: out, as: UTF8.self) + "_pool"
    }

    /// Render the full config fragment for one service.
    static func render(_ d: LBDesiredState) -> String {
        var eps = d.backends
        eps.sort(by: Endpoint.less)
        let pool = upstreamName(d.service)

        var s = "# managed by sctld — service \(d.service)\n"
        s += "# generated by the SwiftCube LB programmer loop (SC6); do not edit by hand\n"

        if eps.isEmpty {
            // Empty pool: a valid config that keeps the listener up and answers 503. Never an
            // empty `upstream {}` (which nginx rejects).
            s += "# no ready endpoints — explicit no-backends response\n"
            s += listenerOpen(d) + indent(healthComment(d.health)) + "    location / {\n"
            s += "        return 503;\n"
            s += "    }\n}\n"
            return s
        }

        // upstream block = the backend pool, one server line per ready endpoint.
        s += "upstream \(pool) {\n"
        for e in eps {
            s += "    server \(e.address):\(e.port) max_fails=3 fail_timeout=10s;"
            s += "  # \(e.cellId)\n"
        }
        s += "}\n"

        // server block = the listener, proxying into the pool.
        s += listenerOpen(d) + indent(healthComment(d.health)) + "    location / {\n"
        s += "        proxy_pass http://\(pool);\n"
        s += "        proxy_next_upstream error timeout http_502 http_503 http_504;\n"
        s += "        proxy_set_header Host $host;\n"
        s += "        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n"
        s += "    }\n}\n"
        return s
    }

    // MARK: - Pieces

    /// The `server {` opener up to (but not including) the location block: the `listen` line
    /// plus, for https, the TLS-cert directives carrying the cert ref.
    private static func listenerOpen(_ d: LBDesiredState) -> String {
        let l = d.listener
        var s = "server {\n"
        switch l.proto {
        case .http:
            s += "    listen \(l.port);\n"
        case .https:
            s += "    listen \(l.port) ssl;\n"
            // TLS-cert provisioning is the secrets/SC9 seam; SC6 threads the ref through so the
            // file path the secrets layer mounts is referenced deterministically.
            s += "    ssl_certificate     /etc/sctld/tls/\(l.tlsCertRef).crt;  # cert ref (SC9 seam)\n"
            s += "    ssl_certificate_key /etc/sctld/tls/\(l.tlsCertRef).key;\n"
        case .tcp:
            // L4 pass-through is a `stream{}` block — recorded as a seam; http/https land first.
            s += "    listen \(l.port);  # tcp/L4 pass-through is an SC6 seam (stream block)\n"
        }
        return s
    }

    /// The configured readiness path, rendered as a comment (open-source nginx checks backends
    /// passively; the active readiness path is owned by SC5's probe runner, not nginx).
    private static func healthComment(_ h: LBHealthCheck) -> String {
        if h.path.isEmpty {
            return "# health: passive (tcp connect); max_fails/fail_timeout above\n"
        }
        let port = h.port == 0 ? "backend port" : "\(h.port)"
        return "# health: readiness \(h.path) on \(port) (probed by slet/SC5; passive here)\n"
    }

    private static func indent(_ s: String) -> String { "    " + s }
}
