#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# build-ncurses.sh — cross-build static ncurses for swift-os (milestone NC1).
#
# Produces:
#   build/ncdemo.elf                         — the proof-of-port demo (-> /bin/ncdemo)
#   sysroot/aarch64-elf/lib/libncurses.a     — static curses lib (for MC later)
#   sysroot/aarch64-elf/include/{curses.h,ncurses.h,term.h,unctrl.h,...}
#
# ncurses is autotools, so this mirrors the cross-build pattern of
# scripts/build-pcre2.sh (env exports + ac_cv_*/cf_cv_* cache-var overrides for
# the compile-AND-run configure probes that cannot execute on the host), and the
# busybox-style direct download (no swport package — NC1 only needs a baked
# binary + a sysroot dev lib, not a signed repo package).
#
# Terminfo: we bake the entries we need INTO libncurses.a via --with-fallbacks,
# so there is NO terminfo database on disk at runtime (swift-os has no such DB).
# Fallback C source is generated by tic/infocmp; on a cross build those must be
# the HOST tools (the cross-built tic can't run here) — pointed at via
# --with-tic-path/--with-infocmp-path.
#
# Requires: `make newlib` first (sysroot), aarch64-elf-gcc/binutils, host
# tic+infocmp (macOS ships them), network for the tarball.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VERSION="${NCURSES_VERSION:-6.5}"
WORK="$ROOT/build/ncurses-port-work"
SRC="$WORK/ncurses-${VERSION}"
TARBALL="$WORK/ncurses-${VERSION}.tar.gz"
URL="${NCURSES_URL:-https://ftp.gnu.org/gnu/ncurses/ncurses-${VERSION}.tar.gz}"
RUNTIME="$ROOT/build/ncurses-port-runtime"
SYSROOT="${NCURSES_SYSROOT:-$ROOT/sysroot/aarch64-elf}"
COMPAT="$ROOT/userland/compat"
CC="${NCURSES_CC:-aarch64-elf-gcc}"
AR="${NCURSES_AR:-aarch64-elf-ar}"
RANLIB="${NCURSES_RANLIB:-aarch64-elf-ranlib}"
READELF="${NCURSES_READELF:-aarch64-elf-readelf}"
NM="${NCURSES_NM:-aarch64-elf-nm}"
STRIP="${NCURSES_STRIP:-aarch64-elf-strip}"
# Fallback generation runs tic/infocmp over ncurses 6.5's terminfo.src; the host
# tools must be >= the source version (Apple's /usr/bin/tic is 6.0 and chokes on
# 6.5 entries). Prefer a homebrew ncurses (6.6) if present, else PATH.
brew_nc="$(brew --prefix ncurses 2>/dev/null || true)"
HOST_TIC="${NCURSES_TIC:-${brew_nc:+$brew_nc/bin/tic}}"
HOST_INFOCMP="${NCURSES_INFOCMP:-${brew_nc:+$brew_nc/bin/infocmp}}"
[[ -n "$HOST_TIC" && -x "$HOST_TIC" ]] || HOST_TIC="$(command -v tic || true)"
[[ -n "$HOST_INFOCMP" && -x "$HOST_INFOCMP" ]] || HOST_INFOCMP="$(command -v infocmp || true)"
JOBS="${JOBS:-4}"

# Terminals baked into the library. vt100/ansi are the conservative serial
# baseline; linux/xterm cover the host terminal the QEMU serial is mirrored
# into; dumb is the graceful-degradation floor.
FALLBACKS="${NCURSES_FALLBACKS:-vt100,ansi,linux,xterm,dumb}"

fail() { printf 'FAIL: %s\n' "$*" >&2; exit 2; }
require_exe() { command -v "$1" >/dev/null 2>&1 || fail "missing executable: $1"; }

require_exe "$CC"
require_exe "$AR"
require_exe "$RANLIB"
require_exe "$READELF"
require_exe "$NM"
require_exe "$STRIP"
require_exe make
require_exe tar
[[ -n "$HOST_TIC" ]]     || fail "missing host tic (needed for --with-fallbacks)"
[[ -n "$HOST_INFOCMP" ]] || fail "missing host infocmp (needed for --with-fallbacks)"
[[ -f "$SYSROOT/lib/libc.a" ]] || fail "newlib sysroot missing. Run: make newlib"

mkdir -p "$WORK" "$RUNTIME" "$ROOT/build"
[[ -f "$TARBALL" ]] || { echo "Fetching ncurses ${VERSION}..."; curl -fsSL -o "$TARBALL" "$URL"; }
rm -rf "$SRC"
tar xzf "$TARBALL" -C "$WORK"

# --- our runtime objects (so configure's link probes resolve) ----------------
inc_flags=(-isystem "$COMPAT" -isystem "$SYSROOT/include")
runtime_cflags=(-ffreestanding -Os "${inc_flags[@]}")
"$CC" "${runtime_cflags[@]}" -c "$ROOT/userland/lib/crt0_newlib.S"     -o "$RUNTIME/crt0_newlib.o"
"$CC" "${runtime_cflags[@]}" -c "$ROOT/userland/lib/newlib_syscalls.c" -o "$RUNTIME/newlib_syscalls.o"
"$CC" "${runtime_cflags[@]}" -c "$ROOT/userland/compat/stubs.c"        -o "$RUNTIME/compat_stubs.o"

configure_ldflags="-static -nostartfiles -nostdlib -T $ROOT/userland/user_newlib.ld -Wl,-z,max-page-size=4096 $RUNTIME/crt0_newlib.o $RUNTIME/newlib_syscalls.o $RUNTIME/compat_stubs.o -L$SYSROOT/lib"
libs="-Wl,--start-group -lc -lm -lgcc -Wl,--end-group"

(
    cd "$SRC"
    export CC AR RANLIB
    export CFLAGS="-ffreestanding -Os -isystem $COMPAT -isystem $SYSROOT/include"
    export CPPFLAGS="-isystem $COMPAT -isystem $SYSROOT/include"
    export LDFLAGS="$configure_ldflags"
    export LIBS="$libs"
    # Host build tools for generated programs (e.g. fallback generation helpers).
    export BUILD_CC="${BUILD_CC:-cc}"
    export BUILD_CFLAGS="${BUILD_CFLAGS:--O2}"
    export BUILD_CPPFLAGS=""
    export BUILD_LDFLAGS=""
    export BUILD_LIBS=""
    # Cross-build cache-var overrides: ncurses runs compile-AND-run configure
    # probes that cannot execute on the host. Seed the known answers for the
    # swift-os target (verified facts: poll works on the tty, fork works,
    # nanosleep is implemented; chtype is a long; bool is 1 byte).
    export cf_cv_working_poll=yes
    export cf_cv_func_nanosleep=yes
    export cf_cv_func_mkstemp=yes
    export cf_cv_type_of_bool=unsigned
    export cf_cv_cc_bool_type=1
    export cf_cv_typeof_chtype=long
    export cf_cv_typeof_mmask_t=long
    export cf_cv_sizechange=yes
    export cf_cv_working_chmod=yes
    export ac_cv_func_fork_works=yes
    export ac_cv_func_vfork_works=yes
    export ac_cv_func_memcmp_working=yes

    ./configure \
        --host=aarch64-elf \
        --prefix=/usr \
        --without-shared --with-normal \
        --with-fallbacks="$FALLBACKS" \
        --with-tic-path="$HOST_TIC" \
        --with-infocmp-path="$HOST_INFOCMP" \
        --disable-widec \
        --without-cxx --without-cxx-binding --without-ada \
        --without-manpages --without-tests --without-progs \
        --disable-db-install --disable-home-terminfo \
        --without-pkg-config --disable-rpath --without-debug \
        --with-termlib=no \
        --disable-dependency-tracking

    make -j"$JOBS" libs
)

LIBNC="$SRC/lib/libncurses.a"
[[ -f "$LIBNC" ]] || fail "libncurses.a not built (see $SRC/config.log / build output)"

# --- install lib + headers into the sysroot (so MC can find them later) ------
mkdir -p "$SYSROOT/lib" "$SYSROOT/include"
cp "$LIBNC" "$SYSROOT/lib/libncurses.a"
"$RANLIB" "$SYSROOT/lib/libncurses.a"
for h in curses.h term.h unctrl.h termcap.h ncurses_dll.h nc_tparm.h; do
    [[ -f "$SRC/include/$h" ]] && cp "$SRC/include/$h" "$SYSROOT/include/$h"
done
# ncurses installs <curses.h>; many consumers (and MC) include <ncurses.h>.
cp "$SRC/include/curses.h" "$SYSROOT/include/ncurses.h"
chmod 0644 "$SYSROOT/lib/libncurses.a" "$SYSROOT/include/"curses.h "$SYSROOT/include/ncurses.h"

# --- build + link the proof-of-port demo -------------------------------------
"$CC" -ffreestanding -Os "${inc_flags[@]}" -I"$SRC/include" \
    -static -nostartfiles -nostdlib -T "$ROOT/userland/user_newlib.ld" \
    -Wl,-z,max-page-size=4096 \
    "$RUNTIME/crt0_newlib.o" \
    "$RUNTIME/newlib_syscalls.o" \
    "$RUNTIME/compat_stubs.o" \
    "$ROOT/userland/ncurses/ncdemo.c" \
    "$LIBNC" \
    -L"$SYSROOT/lib" \
    -Wl,--start-group -lc -lm -lgcc -Wl,--end-group \
    -o "$ROOT/build/ncdemo.elf"

undefined="$("$NM" -u "$ROOT/build/ncdemo.elf")"
[[ -z "$undefined" ]] || fail "ncdemo.elf has undefined symbols: $undefined"
"$READELF" -h "$ROOT/build/ncdemo.elf" | grep -q 'Machine:[[:space:]]*AArch64' ||
    fail "ncdemo.elf is not an AArch64 ELF"
"$STRIP" "$ROOT/build/ncdemo.elf"

# Content stamp so Makefile / CI refuse a binary whose tree-owned runtime
# inputs moved (mtimes alone are unreliable after Actions cache restore).
"$ROOT/scripts/artifact-inputs-hash.sh" ncurses >"$ROOT/build/ncurses.inputs-hash"

echo "Built $ROOT/build/ncdemo.elf"
echo "Installed $SYSROOT/lib/libncurses.a (fallbacks: $FALLBACKS)"
echo "inputs-hash $(cat "$ROOT/build/ncurses.inputs-hash")"
"$READELF" -h "$ROOT/build/ncdemo.elf" | grep -E 'Type:|Entry'
