// SPDX-License-Identifier: Apache-2.0
//
// modelmanifest.swift — host-side model-bundle manifest generator (I5).
//
// Emits the manifest.toml for a /models/<name>/<generation>/ bundle: the
// TOML-subset schema parsed by userland/lib/modelbundle.swift, with SHA-256
// (kernel/crypto/sha256.swift, compiled alongside) and sizes computed from the
// actual payload files. Used by `make base-image` to stage verified bundles.
//
// Usage: modelmanifest <name> <generation> <model.bin> <tokenizer.bin> <out.toml>

import Foundation

@main
struct ModelManifestTool {
    static func die(_ msg: String) -> Never {
        FileHandle.standardError.write(Data("modelmanifest: \(msg)\n".utf8))
        exit(1)
    }

    static func hashFile(_ path: String) -> (String, Int) {
        guard let d = FileManager.default.contents(atPath: path) else {
            die("cannot read \(path)")
        }
        var hex = [UInt8](repeating: 0, count: 64)
        d.withUnsafeBytes { (raw: UnsafeRawBufferPointer) in
            hex.withUnsafeMutableBytes { out in
                sha256Hex(raw.baseAddress!, d.count, out.baseAddress!)
            }
        }
        return (String(decoding: hex, as: UTF8.self), d.count)
    }

    static func main() {
        guard CommandLine.arguments.count == 6 else {
            die("usage: modelmanifest <name> <generation> <model.bin> <tokenizer.bin> <out.toml>")
        }
        let name = CommandLine.arguments[1]
        guard let generation = Int(CommandLine.arguments[2]), generation >= 0 else {
            die("generation must be a non-negative integer")
        }
        let modelPath = CommandLine.arguments[3]
        let tokPath = CommandLine.arguments[4]
        let outPath = CommandLine.arguments[5]

        let (modelHex, modelSize) = hashFile(modelPath)
        let (tokHex, tokSize) = hashFile(tokPath)

        let manifest = """
        # swift-os model bundle manifest (generated by tools/modelmanifest.swift)
        name = "\(name)"
        generation = \(generation)
        format = "llama2c"

        [file.model]
        path = "model.bin"
        sha256 = "\(modelHex)"
        size = \(modelSize)

        [file.tokenizer]
        path = "tokenizer.bin"
        sha256 = "\(tokHex)"
        size = \(tokSize)
        """

        do {
            try (manifest + "\n").write(toFile: outPath, atomically: true, encoding: .utf8)
        } catch {
            die("cannot write \(outPath): \(error)")
        }
        print("modelmanifest: \(name) gen \(generation): model \(modelSize) B \(modelHex.prefix(12))…, tokenizer \(tokSize) B")
    }
}
