// SPDX-License-Identifier: Apache-2.0
//
// sha512.swift — SHA-512 (FIPS 180-4) in pure, Embedded-compatible Swift.
//
// Needed by Ed25519 (RFC 8032 hashes with SHA-512). One-shot API over raw
// pointers, mirroring sha256.swift. The K/H constants below were generated by
// exact integer arithmetic (fractional bits of cube/square roots of the first
// primes), not transcribed by hand; the implementation is pinned by NIST
// vectors in tests/ed25519_test.swift.

private let sha512K: [UInt64] = [
    0x428a2f98d728ae22, 0x7137449123ef65cd, 0xb5c0fbcfec4d3b2f, 0xe9b5dba58189dbbc,
    0x3956c25bf348b538, 0x59f111f1b605d019, 0x923f82a4af194f9b, 0xab1c5ed5da6d8118,
    0xd807aa98a3030242, 0x12835b0145706fbe, 0x243185be4ee4b28c, 0x550c7dc3d5ffb4e2,
    0x72be5d74f27b896f, 0x80deb1fe3b1696b1, 0x9bdc06a725c71235, 0xc19bf174cf692694,
    0xe49b69c19ef14ad2, 0xefbe4786384f25e3, 0x0fc19dc68b8cd5b5, 0x240ca1cc77ac9c65,
    0x2de92c6f592b0275, 0x4a7484aa6ea6e483, 0x5cb0a9dcbd41fbd4, 0x76f988da831153b5,
    0x983e5152ee66dfab, 0xa831c66d2db43210, 0xb00327c898fb213f, 0xbf597fc7beef0ee4,
    0xc6e00bf33da88fc2, 0xd5a79147930aa725, 0x06ca6351e003826f, 0x142929670a0e6e70,
    0x27b70a8546d22ffc, 0x2e1b21385c26c926, 0x4d2c6dfc5ac42aed, 0x53380d139d95b3df,
    0x650a73548baf63de, 0x766a0abb3c77b2a8, 0x81c2c92e47edaee6, 0x92722c851482353b,
    0xa2bfe8a14cf10364, 0xa81a664bbc423001, 0xc24b8b70d0f89791, 0xc76c51a30654be30,
    0xd192e819d6ef5218, 0xd69906245565a910, 0xf40e35855771202a, 0x106aa07032bbd1b8,
    0x19a4c116b8d2d0c8, 0x1e376c085141ab53, 0x2748774cdf8eeb99, 0x34b0bcb5e19b48a8,
    0x391c0cb3c5c95a63, 0x4ed8aa4ae3418acb, 0x5b9cca4f7763e373, 0x682e6ff3d6b2b8a3,
    0x748f82ee5defb2fc, 0x78a5636f43172f60, 0x84c87814a1f0ab72, 0x8cc702081a6439ec,
    0x90befffa23631e28, 0xa4506cebde82bde9, 0xbef9a3f7b2c67915, 0xc67178f2e372532b,
    0xca273eceea26619c, 0xd186b8c721c0c207, 0xeada7dd6cde0eb1e, 0xf57d4f7fee6ed178,
    0x06f067aa72176fba, 0x0a637dc5a2c898a6, 0x113f9804bef90dae, 0x1b710b35131c471b,
    0x28db77f523047d84, 0x32caab7b40c72493, 0x3c9ebe0a15c9bebc, 0x431d67c49c100d4c,
    0x4cc5d4becb3e42b6, 0x597f299cfc657e2a, 0x5fcb6fab3ad6faec, 0x6c44198c4a475817,
]

@inline(__always) private func rotr64(_ x: UInt64, _ n: UInt64) -> UInt64 {
    return (x >> n) | (x << (64 - n))
}

/// One-shot SHA-512: hash `len` bytes at `msg` into 64 bytes at `out64`.
func sha512(_ msg: UnsafeRawPointer, _ len: Int, _ out64: UnsafeMutableRawPointer) {
    var h: [UInt64] = [
        0x6a09e667f3bcc908, 0xbb67ae8584caa73b, 0x3c6ef372fe94f82b, 0xa54ff53a5f1d36f1,
        0x510e527fade682d1, 0x9b05688c2b3e6c1f, 0x1f83d9abfb41bd6b, 0x5be0cd19137e2179,
    ]
    let bytes = msg.assumingMemoryBound(to: UInt8.self)

    // Padded length: message + 0x80 + zeros + 16-byte big-endian bit length
    // (we only need the low 64 bits of the bit count for any realistic input).
    let blocks = (len + 1 + 16 + 127) / 128
    var w = [UInt64](repeating: 0, count: 80)

    for b in 0..<blocks {
        // Load one 128-byte block, with padding materialized on the fly.
        for t in 0..<16 {
            var v: UInt64 = 0
            for i in 0..<8 {
                let idx = b * 128 + t * 8 + i
                var byte: UInt8 = 0
                if idx < len {
                    byte = bytes[idx]
                } else if idx == len {
                    byte = 0x80
                } else if b == blocks - 1 && t >= 14 {
                    // Bit length, big-endian in the last 16 bytes.
                    let bitLen = UInt64(len) << 3
                    let pos = b * 128 + 128 - idx - 1   // bytes from the end - 1
                    if pos < 8 { byte = UInt8(truncatingIfNeeded: bitLen >> (8 * UInt64(pos))) }
                }
                v = (v << 8) | UInt64(byte)
            }
            w[t] = v
        }
        for t in 16..<80 {
            let s0 = rotr64(w[t - 15], 1) ^ rotr64(w[t - 15], 8) ^ (w[t - 15] >> 7)
            let s1 = rotr64(w[t - 2], 19) ^ rotr64(w[t - 2], 61) ^ (w[t - 2] >> 6)
            w[t] = w[t - 16] &+ s0 &+ w[t - 7] &+ s1
        }

        var a = h[0], bb = h[1], c = h[2], d = h[3]
        var e = h[4], f = h[5], g = h[6], hh = h[7]
        for t in 0..<80 {
            let S1 = rotr64(e, 14) ^ rotr64(e, 18) ^ rotr64(e, 41)
            let ch = (e & f) ^ (~e & g)
            let t1 = hh &+ S1 &+ ch &+ sha512K[t] &+ w[t]
            let S0 = rotr64(a, 28) ^ rotr64(a, 34) ^ rotr64(a, 39)
            let maj = (a & bb) ^ (a & c) ^ (bb & c)
            let t2 = S0 &+ maj
            hh = g; g = f; f = e; e = d &+ t1
            d = c; c = bb; bb = a; a = t1 &+ t2
        }
        h[0] &+= a; h[1] &+= bb; h[2] &+= c; h[3] &+= d
        h[4] &+= e; h[5] &+= f; h[6] &+= g; h[7] &+= hh
    }

    let out = out64.assumingMemoryBound(to: UInt8.self)
    for i in 0..<8 {
        for j in 0..<8 {
            out[i * 8 + j] = UInt8(truncatingIfNeeded: h[i] >> (56 - 8 * UInt64(j)))
        }
    }
}
